project:
  type: website
  

website:
  title: "Lektorat \nSarah Zeller"
  page-footer: "Sarah Zeller"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - file: about.qmd
    right:
      - text: "{{< fa envelope >}}"
        href: mailto:s.zeller@posteo.net
  search: false
  cookie-consent: 
    type: express

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    # page-layout: custom

editor: visual

