project:
  type: website
  

website:
  title: "Lektorat Sarah Zeller"
  page-footer: "Sarah Zeller"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  search: false
  cookie-consent: 
    type: express

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    # page-layout: custom

editor: visual

